site_name: Data Structures and Algorithms using Golang
nav:
    - Home: index.md
    - Arrays:
        - Introduction: array/intro.md
        - Operation in Array: array/operations.md
        - Largest Element in Array: array/largest_element.md
        - Second Largest Element in Array: array/second_largest_element.md
        - Check If Array is Sorted: array/is_array_sorted.md
        - Reverse an Array: array/reverse_array.md
    - About: about.md
theme: readthedocs