site_name: Data Structures and Algorithms using Golang
nav:
    - Home: index.md
    - String:
        - String is Palindrom: string/palindrom.md
        - String is Pangram: string/pangram.md
        - Strign is Anagram: string/anagram.md
        - Word cound in paragraph: string/word_count.md
        - Max n Occurance of Word in Paragraph: string/max_word_n_count.md
    - Arrays:
        - Introduction: array/intro.md
        - Operation in Array: array/operations.md
        - Largest Element in Array: array/largest_element.md
        - Second Largest Element in Array: array/second_largest_element.md
        - Check If Array is Sorted: array/is_array_sorted.md
        - Reverse an Array: array/reverse_array.md
        - Remove Duplicate from Sorted Array: array/remove_duplicates_from_sorted_array.md
        - Remove Duplicate from Unsorted Array: array/remove_duplicates_from_unsorted_array.md
        - Move All Zeroes to End: array/move_all_zeroes_to_end.md
        - Left Rotate Array by One: array/left_rotate_array_by_one.md
        - Left Rotate Array by d:  array/left_rotate_array_by_d.md
        - Leaders in Array: array/leaders_in_array.md
        - Maximum Difference: array/maximum_difference.md
        - Frequency in Sorted Array: array/frequency_sorted_array.md
    - About: about.md
theme: readthedocs