name: Deploy MkDocs on GitHub pages

on: 
  push:
    branches:
      - main__2

jobs:
  deploy_mk_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Install mkdocks
        run: pip install mkdocs
      - name: GitHub Deploy
        run: mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
